### ISSUE TITLE
Vertical Rhythm

### ISSUE THREAD

**Issue by VinSpee** [scottkellum/sassconfdesign#1]
Any specific reason you're not using vertical rhythm?

**Comment by scottkellum** [comment]
IMO it’s more of a hassle than it’s worth in website design. I find just using modular-scale and ems provides good typographic consistency without as much hassle.

For print, especially magazine design, I always set up and use a baseline grid. So much easier to deal with in InDesign.

**Comment by VinSpee** [comment]
Even using Compass's vertical-rhythm tools? Have you ever used them?

**Comment by scottkellum** [comment]
I may check it out if this ever goes multi-column. Feel free to fork and play with it if you want.

**Comment by VinSpee** [comment]
Will do!
